"""Markdown writer — turn what an autonomous run did into a deterministic flow.

The lifecycle the framework is built for: AI or a skill explores once, the
successful path is written as ordinary Markdown, QA reviews it, and from
then on it runs deterministically through L1 (L2/L3 only when the page
changes). Two sources:

  steps_to_markdown   the leaf steps a skill executed (fill, click, select,
                      press, back, goto…), with an ``assert_url`` inserted
                      after every step that changed the URL, and an
                      ``assert_text`` for each new heading, dialog title or
                      alert the step brought up (``StepResult.after``) —
                      unless the text looks volatile (numbers, dates, times,
                      amounts, emails), which would make the flow flaky
  graph_to_markdown   explore_page's page/action graph — one section per
                      navigation found (goto the page, click, assert_url)

Generated files are plain flows the parser accepts as they are. URLs stay
absolute (an ``<APP_URL>`` placeholder only resolves when it is the whole
argument), so replace the origin by hand if the flow should follow ``.env``.
"""

from __future__ import annotations

import re

from app.schemas.actions import ActionType, StepResult
from app.utils.urls import path_and_query, same_page

# Steps worth replaying; skills, waits and screenshots are not.
REPLAYABLE = frozenset({
    ActionType.GOTO, ActionType.BACK, ActionType.RELOAD, ActionType.CLICK,
    ActionType.CLICK_LINK_TEXT, ActionType.DOUBLE_CLICK, ActionType.HOVER,
    ActionType.FILL, ActionType.TYPE, ActionType.CLEAR, ActionType.SELECT,
    ActionType.CHECK, ActionType.UNCHECK, ActionType.PRESS, ActionType.SCROLL,
    ActionType.ASSERT_TEXT, ActionType.ASSERT_VISIBLE, ActionType.ASSERT_URL,
    ActionType.WAIT_FOR_TEXT, ActionType.WAIT_FOR_ELEMENT, ActionType.WAIT_LOAD,
})


MAX_ASSERT_LEN = 60
# Two or more digits anywhere ("Showing 1 to 10 of 57", "Order #12", "3/14") is data, not UI.
_VOLATILE_RE = re.compile(r"\d\D*\d|[$€£¥%@\"|]|\b(today|yesterday|tomorrow|ago|am|pm)\b", re.IGNORECASE)


def stable_text(text: str) -> bool:
    """Short, and free of what changes between runs (or cannot be quoted in a step)."""
    return bool(text) and len(text) <= MAX_ASSERT_LEN and not _VOLATILE_RE.search(text)


def _assertions_after(step: StepResult, seen: dict[str, str]) -> list[str]:
    """``assert_text`` lines for what *step* newly brought up; updates *seen*."""
    out: list[str] = []
    if not step.after:                    # nothing captured after this step: nothing learned
        return out
    for key in ("heading", "dialog", "alert"):
        text = step.after.get(key, "")
        if stable_text(text) and seen.get(key) != text:
            out.append(_line("assert_text", text))
        seen[key] = text
    return out


def _replayable(steps: list[StepResult]) -> list[StepResult]:
    return [s for s in steps if not s.group and s.success and s.action.type in REPLAYABLE]


def suggested_assertions(steps: list[StepResult]) -> list[str]:
    """The assertions ``steps_to_markdown`` adds, as step text (``assert_text: "Members"``)."""
    seen: dict[str, str] = {}
    return [line[2:] for s in _replayable(steps) for line in _assertions_after(s, seen)]


def _line(action: str, *args: str) -> str:
    if not args:
        return f"- {action}"
    return f"- {action}: " + " | ".join('"' + a.replace('"', "'") + '"' for a in args)


def _header(title: str, note: str) -> list[str]:
    return [f"# {title}", "", f"<!-- {note} -->", ""]


def steps_to_markdown(title: str, steps: list[StepResult], start_url: str = "",
                      note: str = "generated by the web agent — review before adding to the suite") -> str:
    """One ``## Steps`` section replaying the successful leaf steps in order."""
    lines = _header(title, note) + ["## Steps"]
    if start_url:
        lines.append(_line("goto", start_url))
    last_url = start_url
    seen: dict[str, str] = {}
    for s in _replayable(steps):
        lines.append(_line(s.action.type.value, *s.action.args))
        if s.url and not same_page(s.url, last_url) \
                and s.action.type not in (ActionType.ASSERT_URL, ActionType.GOTO):
            lines.append(_line("assert_url", path_and_query(s.url)))
        lines += [a for a in _assertions_after(s, seen) if a != lines[-1]]
        if s.url:
            last_url = s.url
    return "\n".join(lines) + "\n"


def graph_to_markdown(title: str, graph: dict, start_url: str,
                      note: str = "generated by explore_page — one section per navigation found") -> str:
    """A section per ``navigates`` edge: open the page, press the control, check the URL."""
    lines = _header(title, note)
    sections = 0
    for url, page in graph.items():
        for edge in page.get("edges", []):
            if edge.get("outcome") != "navigates" or not edge.get("to"):
                continue
            sections += 1
            heading = f"{page.get('title') or path_and_query(url)} → {edge['action']}"
            lines += [f"## {heading}", _line("goto", url), _line("click", edge["action"]),
                      _line("assert_url", path_and_query(edge["to"])), ""]
    if not sections:
        lines += ["## Steps", _line("goto", start_url), _line("assert_text", graph.get(start_url, {}).get("title") or ""), ""]
    return "\n".join(lines).rstrip("\n") + "\n"
