"""Markdown writer — turn what an autonomous run did into a deterministic flow.

The lifecycle the framework is built for: AI or a skill explores once, the
successful path is written as ordinary Markdown, QA reviews it, and from
then on it runs deterministically through L1 (L2/L3 only when the page
changes). Two sources:

  steps_to_markdown   the leaf steps a skill executed (fill, click, select,
                      press, back, goto…), with an ``assert_url`` inserted
                      after every step that changed the URL
  graph_to_markdown   explore_page's page/action graph — one section per
                      navigation found (goto the page, click, assert_url)

Generated files are plain flows the parser accepts as they are. URLs stay
absolute (an ``<APP_URL>`` placeholder only resolves when it is the whole
argument), so replace the origin by hand if the flow should follow ``.env``.
"""

from __future__ import annotations

from urllib.parse import urlparse

from app.schemas.actions import ActionType, StepResult

# Steps worth replaying; skills, waits and screenshots are not.
REPLAYABLE = frozenset({
    ActionType.GOTO, ActionType.BACK, ActionType.RELOAD, ActionType.CLICK,
    ActionType.CLICK_LINK_TEXT, ActionType.DOUBLE_CLICK, ActionType.HOVER,
    ActionType.FILL, ActionType.TYPE, ActionType.CLEAR, ActionType.SELECT,
    ActionType.CHECK, ActionType.UNCHECK, ActionType.PRESS, ActionType.SCROLL,
    ActionType.ASSERT_TEXT, ActionType.ASSERT_VISIBLE, ActionType.ASSERT_URL,
    ActionType.WAIT_FOR_TEXT, ActionType.WAIT_FOR_ELEMENT, ActionType.WAIT_LOAD,
})


def _line(action: str, *args: str) -> str:
    if not args:
        return f"- {action}"
    return f"- {action}: " + " | ".join('"' + a.replace('"', "'") + '"' for a in args)


def _path(url: str) -> str:
    p = urlparse(url)
    return (p.path or "/") + (f"?{p.query}" if p.query else "")


def _header(title: str, note: str) -> list[str]:
    return [f"# {title}", "", f"<!-- {note} -->", ""]


def steps_to_markdown(title: str, steps: list[StepResult], start_url: str = "",
                      note: str = "generated by the web agent — review before adding to the suite") -> str:
    """One ``## Steps`` section replaying the successful leaf steps in order."""
    lines = _header(title, note) + ["## Steps"]
    if start_url:
        lines.append(_line("goto", start_url))
    last_url = start_url
    for s in steps:
        if s.group or not s.success or s.action.type not in REPLAYABLE:
            continue
        lines.append(_line(s.action.type.value, *s.action.args))
        if s.url and s.url.split("#", 1)[0] != (last_url or "").split("#", 1)[0] \
                and s.action.type not in (ActionType.ASSERT_URL, ActionType.GOTO):
            lines.append(_line("assert_url", _path(s.url)))
        if s.url:
            last_url = s.url
    return "\n".join(lines) + "\n"


def graph_to_markdown(title: str, graph: dict, start_url: str,
                      note: str = "generated by explore_page — one section per navigation found") -> str:
    """A section per ``navigates`` edge: open the page, press the control, check the URL."""
    lines = _header(title, note)
    sections = 0
    for url, page in graph.items():
        for edge in page.get("edges", []):
            if edge.get("outcome") != "navigates" or not edge.get("to"):
                continue
            sections += 1
            heading = f"{page.get('title') or _path(url)} → {edge['action']}"
            lines += [f"## {heading}", _line("goto", url), _line("click", edge["action"]),
                      _line("assert_url", _path(edge["to"])), ""]
    if not sections:
        lines += ["## Steps", _line("goto", start_url), _line("assert_text", graph.get(start_url, {}).get("title") or ""), ""]
    return "\n".join(lines).rstrip("\n") + "\n"
