"""Markdown writer: generated flows replay the successful leaf steps and parse back."""

from __future__ import annotations

from app.flow.parser import parse_flow_markdown
from app.flow.writer import graph_to_markdown, steps_to_markdown
from app.schemas.actions import ActionType, FlowAction, StepResult


def _step(kind, *args, url="https://x.test/members", success=True, group=False):
    return StepResult(action=FlowAction(type=kind, args=list(args)), success=success,
                      message="", layer_used=1, url=url, group=group)


def test_steps_become_a_replayable_flow_with_url_assertions():
    steps = [
        _step(ActionType.TEST_FORM, group=True),                          # markers are skipped
        _step(ActionType.FILL, "Search", 'Smith "the" 2nd'),
        _step(ActionType.PRESS, "Enter", url="https://x.test/members?q=Smith"),
        _step(ActionType.CLICK, "John Smith", url="https://x.test/members/42"),
        _step(ActionType.CLICK, "Broken", success=False, url="https://x.test/members/42"),
        _step(ActionType.SCREENSHOT, url="https://x.test/members/42"),   # not replayable
        _step(ActionType.BACK, url="https://x.test/members?q=Smith"),
    ]
    md = steps_to_markdown("Members — agent test", steps, "https://x.test/members")
    assert md == (
        "# Members — agent test\n\n"
        "<!-- generated by the web agent — review before adding to the suite -->\n\n"
        "## Steps\n"
        '- goto: "https://x.test/members"\n'
        '- fill: "Search" | "Smith \'the\' 2nd"\n'
        '- press: "Enter"\n'
        '- assert_url: "/members?q=Smith"\n'
        '- click: "John Smith"\n'
        '- assert_url: "/members/42"\n'
        "- back\n"
        '- assert_url: "/members?q=Smith"\n'
    )
    flow = parse_flow_markdown(md)
    assert [a.type.value for a in flow.actions] == [
        "goto", "fill", "press", "assert_url", "click", "assert_url", "back", "assert_url"]
    assert flow.title == "Members — agent test"


def test_graph_becomes_one_section_per_navigation():
    graph = {
        "https://x.test/": {"title": "Home", "edges": [
            {"action": "Members", "outcome": "navigates", "to": "https://x.test/members"},
            {"action": "Add", "outcome": "opens dialog", "to": "Add member"},
            {"action": "Docs", "outcome": "external", "to": "https://example.com/"},
        ]},
        "https://x.test/members": {"title": "Members", "edges": [
            {"action": "Home", "outcome": "navigates", "to": "https://x.test/"},
        ]},
    }
    md = graph_to_markdown("Explore Home", graph, "https://x.test/")
    flow = parse_flow_markdown(md)
    assert [a.section for a in flow.actions] == ["Home → Members"] * 3 + ["Members → Home"] * 3
    assert [a.type.value for a in flow.actions] == ["goto", "click", "assert_url"] * 2
    assert flow.actions[2].args == ["/members"]


def test_graph_without_navigations_still_yields_a_flow():
    md = graph_to_markdown("Explore", {"https://x.test/": {"title": "Home", "edges": []}}, "https://x.test/")
    flow = parse_flow_markdown(md)
    assert [(a.type.value, a.args) for a in flow.actions] == [
        ("goto", ["https://x.test/"]), ("assert_text", ["Home"])]


def test_assertions_follow_what_each_step_brought_up():
    from app.flow.writer import steps_to_markdown, suggested_assertions
    from app.schemas.actions import ActionType, FlowAction, StepResult

    def step(kind, *args, after=None, url="https://x.test/members"):
        return StepResult(action=FlowAction(type=kind, args=list(args)), success=True, message="",
                          url=url, after=after or {})

    steps = [
        step(ActionType.CLICK, "Members", after={"heading": "Members", "dialog": "", "alert": ""}),
        step(ActionType.CLICK, "Sort", after={"heading": "Members", "dialog": "", "alert": ""}),   # nothing new
        step(ActionType.CLICK, "View", after={"heading": "Members", "dialog": "Member profile", "alert": ""}),
        step(ActionType.PRESS, "Escape", after={"heading": "Members", "dialog": "", "alert": "Saved 3 min ago"}),
        step(ActionType.CLICK, "View", after={"heading": "Members", "dialog": "Member profile", "alert": ""}),
        step(ActionType.FILL, "Search", "x"),                                   # no capture: changes nothing
        step(ActionType.PRESS, "Enter", after={"heading": "Members", "dialog": "Member profile",
                                               "alert": "Showing 1 to 10 of 57 entries"}),
    ]
    assert suggested_assertions(steps) == [
        'assert_text: "Members"', 'assert_text: "Member profile"', 'assert_text: "Member profile"']
    md = steps_to_markdown("T", steps, "https://x.test/members")
    assert md.count('- assert_text: "Member profile"') == 2 and "Saved 3 min ago" not in md


def test_stable_text_rejects_volatile_values():
    from app.flow.writer import stable_text
    assert stable_text("Member Details")
    for volatile in ("Order #12345", "Updated 2 min ago", "3/14/2026", "Total: $40", "a@b.com",
                     "Showing 1 to 10 of 57 entries", "Step 2 of 4",
                     'He said "hi"', "x" * 61, ""):
        assert not stable_text(volatile), volatile
